name: Hello_world
on:
  issues:
    workflow_dispatch:
    types: [opened, edited, closed]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ready_for_review]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! Today is $(date +'%Y-%m-%d %H:%M:%S')
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
