on:
  issues:
    types: [opened, edited, closed]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ready_for_review]
  gollum:
  workflow_dispatch:
jobs:
  test_schedule:
    runs-on: ubuntu-latest
  build:
    runs-on: ubuntu-latest, macos-latest, windows-latest
    steps:
      - name: Version
        run: sam --version
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world! Today is $(date +'%Y-%m-%d %H:%M:%S')
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
